services:
  - type: web
    name: nextgeneditor-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    rootDir: server
    envVars:
      - key: PORT
        value: 5005
      - key: NODE_VERSION
        value: 20
      - key: MONGO_URI
        fromValue: ${MONGO_URI}
      - key: JWT_SECRET
        fromValue: ${JWT_SECRET}
      - key: GROQ_API_KEY
        fromValue: ${GROQ_API_KEY}
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: NODE_ENV
        value: production
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        fromValue: ${SMTP_USER}
      - key: SMTP_PASS
        fromValue: ${SMTP_PASS}
      - key: FROM_EMAIL
        fromValue: ${FROM_EMAIL}
      - key: CLIENT_URL
        fromValue: ${CLIENT_URL}
